In [3]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_csv('../data/Nike_Sales_Uncleaned.csv')

In [5]:
df.head()

,Order_ID,Gender_Category,Product_Line,Product_Name,Size,Units_Sold,MRP,Discount_Applied,Revenue,Order_Date,Sales_Channel,Region,Profit
0,2000,Kids,Training,SuperRep Go,M,NaN,NaN,0.47,0.0,2024-03-09,Online,bengaluru,-770.45
1,2001,Women,Soccer,Tiempo Legend,M,3.0,4957.93,NaN,0.0,2024-07-09,Retail,Hyd,-112.53
2,2002,Women,Soccer,Premier III,M,4.0,NaN,NaN,0.0,NaN,Retail,Mumbai,3337.34
3,2003,Kids,Lifestyle,Blazer Mid,L,NaN,9673.57,NaN,0.0,04-10-2024,Online,Pune,3376.85
4,2004,Kids,Running,React Infinity,XL,NaN,NaN,NaN,0.0,2024/09/12,Retail,Delhi,187.89

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2500 entries, 0 to 2499
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Order_ID          2500 non-null   int64
 1   Gender_Category   2500 non-null   str
 2   Product_Line      2500 non-null   str
 3   Product_Name      2500 non-null   str
 4   Size              1990 non-null   str
 5   Units_Sold        1265 non-null   float64
 6   MRP               1246 non-null   float64
 7   Discount_Applied  832 non-null    float64
 8   Revenue           2500 non-null   float64
 9   Order_Date        1884 non-null   str
 10  Sales_Channel     2500 non-null   str
 11  Region            2500 non-null   str
 12  Profit            2500 non-null   float64
dtypes: float64(5), int64(1), str(7)
memory usage: 254.0 KB

In [7]:
df.columns

Index(['Order_ID', 'Gender_Category', 'Product_Line', 'Product_Name', 'Size',
       'Units_Sold', 'MRP', 'Discount_Applied', 'Revenue', 'Order_Date',
       'Sales_Channel', 'Region', 'Profit'],
      dtype='str')

In [8]:
df.isnull().sum()

Order_ID               0
Gender_Category        0
Product_Line           0
Product_Name           0
Size                 510
Units_Sold          1235
MRP                 1254
Discount_Applied    1668
Revenue                0
Order_Date           616
Sales_Channel          0
Region                 0
Profit                 0
dtype: int64

In [9]:
df[['Units_Sold', 'MRP', 'Revenue']].head()

   Units_Sold      MRP  Revenue
0         NaN      NaN      0.0
1         3.0  4957.93      0.0
2         4.0      NaN      0.0
3         NaN  9673.57      0.0
4         NaN      NaN      0.0

In [10]:
df.columns

Index(['Order_ID', 'Gender_Category', 'Product_Line', 'Product_Name', 'Size',
       'Units_Sold', 'MRP', 'Discount_Applied', 'Revenue', 'Order_Date',
       'Sales_Channel', 'Region', 'Profit'],
      dtype='str')

In [11]:
df.columns = df.columns.str.lower()

In [12]:
df.columns

Index(['order_id', 'gender_category', 'product_line', 'product_name', 'size',
       'units_sold', 'mrp', 'discount_applied', 'revenue', 'order_date',
       'sales_channel', 'region', 'profit'],
      dtype='str')

In [13]:
df.dtypes

order_id              int64
gender_category         str
product_line            str
product_name            str
size                    str
units_sold          float64
mrp                 float64
discount_applied    float64
revenue             float64
order_date              str
sales_channel           str
region                  str
profit              float64
dtype: object

In [14]:
df['order_date']

0       2024-03-09
1       2024-07-09
2              NaN
3       04-10-2024
4       2024/09/12
           ...
2495    2025-05-14
2496           NaN
2497    02-07-2025
2498    11-12-2024
2499    23-11-2024
Name: order_date, Length: 2500, dtype: str

In [15]:
df['order_date'].unique()

<StringArray>
['2024-03-09', '2024-07-09',          nan, '04-10-2024', '2024/09/12',
 '04-06-2025', '11-10-2024', '2025/01/16', '13-11-2024', '19-09-2024',
 ...
 '2023-12-16', '2024-10-28', '2024-09-03', '2023-11-27', '05-05-2025',
 '2024-07-16', '21-08-2024', '2025-04-02', '12-02-2025', '2025-05-14']
Length: 1009, dtype: str

In [16]:
df['order_date'].value_counts()

order_date
17-11-2024    6
10-12-2024    6
2024/12/16    6
19-07-2025    6
2024/11/10    6
             ..
2024-07-16    1
21-08-2024    1
2025-04-02    1
12-02-2025    1
2025-05-14    1
Name: count, Length: 1008, dtype: int64

In [17]:
df['order_date'] = pd.to_datetime(df['order_date'], format='mixed', errors='coerce')

In [18]:
df['order_date']

0      2024-03-09
1      2024-07-09
2             NaT
3      2024-04-10
4      2024-09-12
          ...
2495   2025-05-14
2496          NaT
2497   2025-02-07
2498   2024-11-12
2499   2024-11-23
Name: order_date, Length: 2500, dtype: datetime64[us]

In [19]:
df.isnull().sum()

order_id               0
gender_category        0
product_line           0
product_name           0
size                 510
units_sold          1235
mrp                 1254
discount_applied    1668
revenue                0
order_date           616
sales_channel          0
region                 0
profit                 0
dtype: int64

In [20]:
df['units_sold'].unique()

array([nan,  3.,  4.,  1., -1.,  0.,  2.])

In [21]:
df.shape

(2500, 13)

In [22]:
df['units_sold'].value_counts()

units_sold
 2.0    234
 0.0    224
 4.0    212
-1.0    205
 1.0    203
 3.0    187
Name: count, dtype: int64

In [23]:
df.head()

,order_id,gender_category,product_line,product_name,size,units_sold,mrp,discount_applied,revenue,order_date,sales_channel,region,profit
0,2000,Kids,Training,SuperRep Go,M,NaN,NaN,0.47,0.0,2024-03-09,Online,bengaluru,-770.45
1,2001,Women,Soccer,Tiempo Legend,M,3.0,4957.93,NaN,0.0,2024-07-09,Retail,Hyd,-112.53
2,2002,Women,Soccer,Premier III,M,4.0,NaN,NaN,0.0,NaT,Retail,Mumbai,3337.34
3,2003,Kids,Lifestyle,Blazer Mid,L,NaN,9673.57,NaN,0.0,2024-04-10,Online,Pune,3376.85
4,2004,Kids,Running,React Infinity,XL,NaN,NaN,NaN,0.0,2024-09-12,Retail,Delhi,187.89

In [24]:
df['size'].unique()

<StringArray>
['M', 'L', 'XL', '11', nan, '9', '6', '12', '7', '10', '8']
Length: 11, dtype: str

In [25]:
df['discount_applied'].unique()

array([0.47,  nan, 0.32, 0.86, 0.3 , 1.17, 0.67, 0.66, 0.5 , 0.16, 0.22,
       1.05, 0.82, 1.07, 0.38, 1.01, 0.83, 0.63, 0.77, 1.04, 0.57, 0.37,
       0.94, 0.78, 0.49, 0.85, 0.21, 0.45, 0.6 , 1.13, 0.29, 0.69, 0.27,
       0.42, 1.14, 0.53, 0.41, 1.24, 0.24, 0.74, 0.95, 1.1 , 1.12, 0.48,
       0.09, 0.8 , 0.01, 1.06, 1.2 , 1.16, 0.59, 0.9 , 0.51, 0.65, 0.97,
       0.36, 0.11, 0.12, 0.31, 0.89, 0.84, 0.39, 0.54, 1.08, 1.03, 0.07,
       1.22, 0.26, 0.25, 0.81, 0.08, 0.71, 0.56, 0.06, 0.91, 0.93, 1.23,
       0.34, 0.05, 0.35, 0.88, 1.02, 1.25, 1.19, 0.2 , 0.03, 1.11, 0.14,
       0.15, 1.15, 0.1 , 0.79, 0.04, 0.19, 0.62, 1.09, 0.33, 0.18, 0.75,
       0.99, 0.55, 0.72, 0.76, 0.7 , 0.44, 1.18, 0.43, 1.21, 0.73, 1.  ,
       0.02, 0.68, 0.96, 0.23, 0.98, 0.61, 0.28, 0.58, 0.46, 0.17, 0.87,
       0.13, 0.52, 0.4 , 0.92, 0.64, 0.  ])

In [26]:
df = df.dropna(subset= ['order_date'])

In [27]:
df['order_date']

0      2024-03-09
1      2024-07-09
3      2024-04-10
4      2024-09-12
6      2025-04-06
          ...
2494   2025-12-02
2495   2025-05-14
2497   2025-02-07
2498   2024-11-12
2499   2024-11-23
Name: order_date, Length: 1884, dtype: datetime64[us]

In [28]:
df.isnull().sum()

order_id               0
gender_category        0
product_line           0
product_name           0
size                 393
units_sold           930
mrp                  945
discount_applied    1240
revenue                0
order_date             0
sales_channel          0
region                 0
profit                 0
dtype: int64

In [29]:
df['size'] = df['size'].fillna('unknown')

In [30]:
df['size'].unique()

<StringArray>
['M', 'L', 'XL', '11', 'unknown', '9', '6', '12', '10', '8', '7']
Length: 11, dtype: str

In [31]:
df['discount_applied'].unique()

array([0.47,  nan, 0.86, 0.32, 0.67, 0.66, 0.5 , 0.16, 1.05, 0.82, 1.07,
       0.38, 0.63, 0.77, 0.37, 0.94, 0.78, 0.49, 0.85, 0.21, 0.45, 0.6 ,
       0.69, 0.27, 0.42, 1.14, 1.13, 0.41, 1.24, 0.24, 0.74, 0.95, 1.1 ,
       1.12, 0.48, 0.09, 0.01, 1.06, 1.2 , 0.59, 0.9 , 0.65, 0.36, 0.11,
       0.12, 0.31, 0.89, 0.84, 0.39, 0.54, 1.08, 1.03, 0.07, 1.22, 0.26,
       0.53, 0.25, 0.81, 0.29, 0.71, 0.56, 0.06, 0.22, 0.91, 1.23, 1.04,
       0.05, 0.35, 0.88, 1.02, 1.25, 0.2 , 0.03, 1.11, 1.15, 0.1 , 0.79,
       0.04, 0.19, 0.62, 0.8 , 0.18, 0.75, 0.99, 0.14, 0.55, 0.72, 0.76,
       0.7 , 0.44, 1.18, 1.01, 0.43, 1.21, 0.73, 1.  , 0.57, 0.68, 0.96,
       1.17, 0.15, 0.98, 0.61, 0.33, 0.3 , 0.58, 0.23, 0.46, 0.08, 0.97,
       0.17, 0.51, 0.13, 0.52, 0.4 , 1.16, 1.09, 0.83, 0.87, 0.64, 0.92,
       0.34, 0.02, 0.28, 1.19, 0.  ])

In [32]:
disc_filt = df['discount_applied'] > 1

In [33]:
df.loc[disc_filt, 'discount_applied'] = np.nan

In [34]:
df['discount_applied'].unique()

array([0.47,  nan, 0.86, 0.32, 0.67, 0.66, 0.5 , 0.16, 0.82, 0.38, 0.63,
       0.77, 0.37, 0.94, 0.78, 0.49, 0.85, 0.21, 0.45, 0.6 , 0.69, 0.27,
       0.42, 0.41, 0.24, 0.74, 0.95, 0.48, 0.09, 0.01, 0.59, 0.9 , 0.65,
       0.36, 0.11, 0.12, 0.31, 0.89, 0.84, 0.39, 0.54, 0.07, 0.26, 0.53,
       0.25, 0.81, 0.29, 0.71, 0.56, 0.06, 0.22, 0.91, 0.05, 0.35, 0.88,
       0.2 , 0.03, 0.1 , 0.79, 0.04, 0.19, 0.62, 0.8 , 0.18, 0.75, 0.99,
       0.14, 0.55, 0.72, 0.76, 0.7 , 0.44, 0.43, 0.73, 1.  , 0.57, 0.68,
       0.96, 0.15, 0.98, 0.61, 0.33, 0.3 , 0.58, 0.23, 0.46, 0.08, 0.97,
       0.17, 0.51, 0.13, 0.52, 0.4 , 0.83, 0.87, 0.64, 0.92, 0.34, 0.02,
       0.28, 0.  ])

In [35]:
df['discount_applied'] = df['discount_applied'].fillna(0)

In [36]:
df['discount_applied'].unique()

array([0.47, 0.  , 0.86, 0.32, 0.67, 0.66, 0.5 , 0.16, 0.82, 0.38, 0.63,
       0.77, 0.37, 0.94, 0.78, 0.49, 0.85, 0.21, 0.45, 0.6 , 0.69, 0.27,
       0.42, 0.41, 0.24, 0.74, 0.95, 0.48, 0.09, 0.01, 0.59, 0.9 , 0.65,
       0.36, 0.11, 0.12, 0.31, 0.89, 0.84, 0.39, 0.54, 0.07, 0.26, 0.53,
       0.25, 0.81, 0.29, 0.71, 0.56, 0.06, 0.22, 0.91, 0.05, 0.35, 0.88,
       0.2 , 0.03, 0.1 , 0.79, 0.04, 0.19, 0.62, 0.8 , 0.18, 0.75, 0.99,
       0.14, 0.55, 0.72, 0.76, 0.7 , 0.44, 0.43, 0.73, 1.  , 0.57, 0.68,
       0.96, 0.15, 0.98, 0.61, 0.33, 0.3 , 0.58, 0.23, 0.46, 0.08, 0.97,
       0.17, 0.51, 0.13, 0.52, 0.4 , 0.83, 0.87, 0.64, 0.92, 0.34, 0.02,
       0.28])

In [37]:
df['revenue'].unique()

array([    0.  , -2409.48,  2514.99,  1118.93,  8190.84, 12010.21,
        5499.82,  4735.44,  3445.74, 16022.36,  6900.2 ,   475.14,
       15837.  , -2970.77, 25079.88, -1799.14,  4178.88,  5869.97,
        9158.23,  3969.91,  -290.08, -1553.23, -2810.35,   425.13,
        -634.04, 13285.66,  7127.85,  8505.19,  3528.68,  3761.39,
        5590.58, -5679.23,  4403.21,  5815.15,  8687.88,  2305.23,
        -655.2 ,  7864.9 ,  8031.86,  7953.88,   -75.04,  3277.55,
        3544.81,  -628.07, -1059.58,  2094.91,  3256.07, 18824.63,
        -635.22, -3545.18,  7953.1 ,   393.59,  4612.57,  8982.51,
       -1766.44,  8781.29,  1852.75,  3745.62, -4088.34,  6066.79,
        2445.59, -2525.97,   236.32,  3593.01, -1909.29, 13528.26,
       -1971.78,  3759.41,  2323.84,  8095.35, -4587.99, 15379.41,
        9260.68, -1396.27, -7561.59, 12412.9 ,  1400.14,  4418.41,
        2175.91,  6498.22,  -998.81,  3739.85,  -109.28,  4166.9 ,
        -193.9 , 14539.45,  2120.5 , -3878.37,  9152.81,  7281.3 ,
        6828.72, 14283.55,  -558.9 ,  7026.48, 10224.99, 20716.55,
        3966.72,   157.68, 26105.37,   420.  ,  8318.58, -1506.9 ,
       -3389.09, 10488.01, 21586.98, 10261.03, -2328.1 ,  -865.55,
        3959.56,  6666.68,  4483.43,  -838.79,  -643.57, -2391.98,
         733.  , -1197.4 ,  1161.18,   482.47,  8783.1 , -4013.04,
       -2960.09,  6257.1 ,  4530.7 , 22459.88,   596.76, -3727.64,
       -5010.39,  5205.44,  4995.81, -2158.22,  9981.04, -2370.08,
        3589.15])

In [38]:
df[['units_sold', 'mrp', 'discount_applied', 'revenue', 'profit']].head(50)

    units_sold      mrp  discount_applied  revenue   profit
0          NaN      NaN              0.47     0.00  -770.45
1          3.0  4957.93              0.00     0.00  -112.53
3          NaN  9673.57              0.00     0.00  3376.85
4          NaN      NaN              0.00     0.00   187.89
6          NaN  6819.78              0.00     0.00  1802.09
8         -1.0      NaN              0.00     0.00  -731.18
10         1.0  7949.83              0.00     0.00  1965.56
12        -1.0      NaN              0.86     0.00  2109.48
13         NaN  9671.05              0.00     0.00   299.34
14         NaN      NaN              0.00     0.00 -1044.40
15         NaN  3285.52              0.00     0.00  1193.21
17         4.0      NaN              0.00     0.00  1946.24
19         0.0  3424.06              0.32     0.00  1915.24
20        -1.0      NaN              0.67     0.00   439.96
21        -1.0  7086.70              0.66 -2409.48 -1120.49
22         NaN      NaN              0.00     0.00  3427.16
23         NaN  5003.95              0.00     0.00  1498.37
24         0.0      NaN              0.50     0.00  1842.35
26         1.0      NaN              0.16     0.00  2301.64
29         0.0      NaN              0.00     0.00  -185.67
30         NaN      NaN              0.00     0.00  -122.93
31         4.0  3493.04              0.82  2514.99   350.70
32         1.0      NaN              0.00     0.00  -555.16
34         NaN  6235.71              0.00     0.00  -267.37
35         4.0      NaN              0.38     0.00  2914.83
36         3.0      NaN              0.00     0.00  -143.80
39         NaN  2767.70              0.63     0.00  -336.30
40         3.0  5075.22              0.00     0.00   145.08
41         NaN  5553.88              0.00     0.00  2371.66
42         NaN      NaN              0.00     0.00  -862.16
43         NaN  3492.89              0.77     0.00  3770.75
44         NaN      NaN              0.00     0.00  2174.71
45         4.0      NaN              0.00     0.00  1833.94
47         1.0  8577.75              0.00     0.00  2888.68
48         NaN      NaN              0.00     0.00  2875.86
51         NaN      NaN              0.37     0.00  3135.98
52         3.0  9155.96              0.00     0.00  2184.80
53         3.0  6009.58              0.00     0.00  3384.92
54        -1.0      NaN              0.00     0.00  -549.76
55         NaN      NaN              0.00     0.00 -1078.76
56         3.0      NaN              0.00     0.00  -244.44
57         3.0  6216.29              0.94  1118.93  -642.02
59        -1.0  9507.54              0.00     0.00   291.28
60         2.0  7979.26              0.00     0.00  2821.59
61         NaN      NaN              0.00     0.00  -501.68
62         2.0      NaN              0.00     0.00  1823.91
63         1.0  9751.00              0.16  8190.84  1130.31
64         2.0  7557.71              0.00     0.00  3277.44
65         NaN      NaN              0.78     0.00    21.58
66        -1.0  5259.05              0.00     0.00  1022.82

In [39]:
df[df['units_sold'] <= 0]

,order_id,gender_category,product_line,product_name,size,units_sold,mrp,discount_applied,revenue,order_date,sales_channel,region,profit
8,2008,Women,Soccer,Premier III,11,-1.0,NaN,0.00,0.00,2024-11-10,Online,Hyderabad,-731.18
12,2018,Kids,Lifestyle,Blazer Mid,unknown,-1.0,NaN,0.86,0.00,2024-11-13,Online,Delhi,2109.48
19,2019,Kids,Running,Air Zoom,6,0.0,3424.06,0.32,0.00,2025-01-17,Online,Hyderabad,1915.24
20,2020,Kids,Soccer,Tiempo Legend,L,-1.0,NaN,0.67,0.00,2025-03-28,Retail,Mumbai,439.96
21,2021,Men,Running,Free RN,L,-1.0,7086.70,0.66,-2409.48,2024-11-19,Retail,Hyd,-1120.49
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2447,4447,Kids,Running,Free RN,XL,0.0,NaN,0.00,0.00,2024-12-12,Retail,Delhi,1574.91
2449,4449,Men,Lifestyle,Air Force 1,9,0.0,5053.29,0.00,0.00,2025-02-24,Retail,Kolkata,3206.34
2451,4451,Women,Lifestyle,Dunk Low,unknown,0.0,2049.73,0.00,0.00,2024-08-11,Online,Pune,2543.16
2457,2019,Men,Lifestyle,Air Force 1,L,-1.0,2452.52,0.12,-2158.22,2024-07-26,Retail,Hyd,-1199.45
2490,4490,Women,Training,Metcon 7,L,0.0,NaN,0.00,0.00,2025-02-23,Online,Kolkata,-1173.84

In [40]:
def get_transaction_type(quantity):
    if pd.isna(quantity):
        return 'Unknown'
    elif quantity > 0:
        return 'Sale'
    elif quantity < 0:
        return 'Return'
    else:
        return 'No Sale'

df['transaction_type'] = df['units_sold'].apply(get_transaction_type)

In [41]:
df[['units_sold', 'transaction_type']].head()

   units_sold transaction_type
0         NaN          Unknown
1         3.0             Sale
3         NaN          Unknown
4         NaN          Unknown
6         NaN          Unknown

In [42]:
units_sold_G0 = (df['units_sold'] > 0 )

In [43]:
df.loc[units_sold_G0].head()

,order_id,gender_category,product_line,product_name,size,units_sold,mrp,discount_applied,revenue,order_date,sales_channel,region,profit,transaction_type
1,2001,Women,Soccer,Tiempo Legend,M,3.0,4957.93,0.00,0.00,2024-07-09,Retail,Hyd,-112.53,Sale
10,2010,Kids,Lifestyle,Waffle One,L,1.0,7949.83,0.00,0.00,2025-01-16,Online,Pune,1965.56,Sale
17,2017,Women,Basketball,Air Jordan,9,4.0,NaN,0.00,0.00,2025-03-17,Retail,Delhi,1946.24,Sale
26,2026,Kids,Lifestyle,Blazer Mid,XL,1.0,NaN,0.16,0.00,2024-08-10,Retail,Kolkata,2301.64,Sale
31,2031,Men,Soccer,Premier III,unknown,4.0,3493.04,0.82,2514.99,2024-05-09,Online,Delhi,350.70,Sale

In [44]:
df.head()

,order_id,gender_category,product_line,product_name,size,units_sold,mrp,discount_applied,revenue,order_date,sales_channel,region,profit,transaction_type
0,2000,Kids,Training,SuperRep Go,M,NaN,NaN,0.47,0.0,2024-03-09,Online,bengaluru,-770.45,Unknown
1,2001,Women,Soccer,Tiempo Legend,M,3.0,4957.93,0.00,0.0,2024-07-09,Retail,Hyd,-112.53,Sale
3,2003,Kids,Lifestyle,Blazer Mid,L,NaN,9673.57,0.00,0.0,2024-04-10,Online,Pune,3376.85,Unknown
4,2004,Kids,Running,React Infinity,XL,NaN,NaN,0.00,0.0,2024-09-12,Retail,Delhi,187.89,Unknown
6,2006,Men,Training,SuperRep Go,M,NaN,6819.78,0.00,0.0,2025-04-06,Online,Bangalore,1802.09,Unknown

In [45]:
df['revenue_clean'] = np.where(
    (df['units_sold'] > 0) & (df['mrp'].notna()),
    df['units_sold'] * df['mrp'] * (1 - df['discount_applied']),
    np.nan
)

In [46]:
df[['units_sold', 'mrp', 'discount_applied', 'revenue', 'revenue_clean']].head(50)

    units_sold      mrp  discount_applied  revenue  revenue_clean
0          NaN      NaN              0.47     0.00            NaN
1          3.0  4957.93              0.00     0.00     14873.7900
3          NaN  9673.57              0.00     0.00            NaN
4          NaN      NaN              0.00     0.00            NaN
6          NaN  6819.78              0.00     0.00            NaN
8         -1.0      NaN              0.00     0.00            NaN
10         1.0  7949.83              0.00     0.00      7949.8300
12        -1.0      NaN              0.86     0.00            NaN
13         NaN  9671.05              0.00     0.00            NaN
14         NaN      NaN              0.00     0.00            NaN
15         NaN  3285.52              0.00     0.00            NaN
17         4.0      NaN              0.00     0.00            NaN
19         0.0  3424.06              0.32     0.00            NaN
20        -1.0      NaN              0.67     0.00            NaN
21        -1.0  7086.70              0.66 -2409.48            NaN
22         NaN      NaN              0.00     0.00            NaN
23         NaN  5003.95              0.00     0.00            NaN
24         0.0      NaN              0.50     0.00            NaN
26         1.0      NaN              0.16     0.00            NaN
29         0.0      NaN              0.00     0.00            NaN
30         NaN      NaN              0.00     0.00            NaN
31         4.0  3493.04              0.82  2514.99      2514.9888
32         1.0      NaN              0.00     0.00            NaN
34         NaN  6235.71              0.00     0.00            NaN
35         4.0      NaN              0.38     0.00            NaN
36         3.0      NaN              0.00     0.00            NaN
39         NaN  2767.70              0.63     0.00            NaN
40         3.0  5075.22              0.00     0.00     15225.6600
41         NaN  5553.88              0.00     0.00            NaN
42         NaN      NaN              0.00     0.00            NaN
43         NaN  3492.89              0.77     0.00            NaN
44         NaN      NaN              0.00     0.00            NaN
45         4.0      NaN              0.00     0.00            NaN
47         1.0  8577.75              0.00     0.00      8577.7500
48         NaN      NaN              0.00     0.00            NaN
51         NaN      NaN              0.37     0.00            NaN
52         3.0  9155.96              0.00     0.00     27467.8800
53         3.0  6009.58              0.00     0.00     18028.7400
54        -1.0      NaN              0.00     0.00            NaN
55         NaN      NaN              0.00     0.00            NaN
56         3.0      NaN              0.00     0.00            NaN
57         3.0  6216.29              0.94  1118.93      1118.9322
59        -1.0  9507.54              0.00     0.00            NaN
60         2.0  7979.26              0.00     0.00     15958.5200
61         NaN      NaN              0.00     0.00            NaN
62         2.0      NaN              0.00     0.00            NaN
63         1.0  9751.00              0.16  8190.84      8190.8400
64         2.0  7557.71              0.00     0.00     15115.4200
65         NaN      NaN              0.78     0.00            NaN
66        -1.0  5259.05              0.00     0.00            NaN

In [47]:
df['transaction_type'].value_counts()

transaction_type
Unknown    930
Sale       632
No Sale    164
Return     158
Name: count, dtype: int64

In [48]:
df['revenue_clean'].describe()

count      313.000000
mean     13093.980373
std       8887.735067
min        236.315400
25%       6066.788000
50%      10488.007200
75%      18627.960000
max      39984.880000
Name: revenue_clean, dtype: float64

In [49]:
df.isnull().sum()

order_id               0
gender_category        0
product_line           0
product_name           0
size                   0
units_sold           930
mrp                  945
discount_applied       0
revenue                0
order_date             0
sales_channel          0
region                 0
profit                 0
transaction_type       0
revenue_clean       1571
dtype: int64

In [50]:
df.head()

,order_id,gender_category,product_line,product_name,size,units_sold,mrp,discount_applied,revenue,order_date,sales_channel,region,profit,transaction_type,revenue_clean
0,2000,Kids,Training,SuperRep Go,M,NaN,NaN,0.47,0.0,2024-03-09,Online,bengaluru,-770.45,Unknown,NaN
1,2001,Women,Soccer,Tiempo Legend,M,3.0,4957.93,0.00,0.0,2024-07-09,Retail,Hyd,-112.53,Sale,14873.79
3,2003,Kids,Lifestyle,Blazer Mid,L,NaN,9673.57,0.00,0.0,2024-04-10,Online,Pune,3376.85,Unknown,NaN
4,2004,Kids,Running,React Infinity,XL,NaN,NaN,0.00,0.0,2024-09-12,Retail,Delhi,187.89,Unknown,NaN
6,2006,Men,Training,SuperRep Go,M,NaN,6819.78,0.00,0.0,2025-04-06,Online,Bangalore,1802.09,Unknown,NaN

In [51]:
df.groupby('product_name')['profit'].sum().sort_values(ascending=False).head()

product_name
LeBron 20      150931.72
Blazer Mid     149100.67
SuperRep Go    144374.08
Waffle One     143755.98
Phantom GT     142701.74
Name: profit, dtype: float64

In [52]:
df['product_name'].value_counts()

product_name
Air Jordan            109
SuperRep Go           107
LeBron 20             107
Waffle One            105
ZoomX Invincible      103
React Infinity        101
Phantom GT            101
Blazer Mid            100
Flex Trainer           97
Dunk Low               95
Premier III            93
Zoom Freak             92
Metcon 7               90
Kyrie Flytrap          88
Air Force 1            88
Free RN                86
Tiempo Legend          85
Mercurial Superfly     83
Air Zoom               78
Pegasus Turbo          76
Name: count, dtype: int64

In [53]:
df['region'].unique()

<StringArray>
['bengaluru',       'Hyd',      'Pune',     'Delhi', 'Bangalore', 'Hyderabad',
  'hyderbad',   'Kolkata',    'Mumbai']
Length: 9, dtype: str

In [54]:
region_map = {
    'Hyd': 'Hyderabad',
    'Hyderbad': 'Hyderabad',
    'Bengaluru': 'Bangalore'
}

df['region'] = df['region'].replace(region_map)

In [55]:
df['region'] = df['region'].str.strip().str.capitalize()

In [56]:
df['region'].unique()

<StringArray>
['Bengaluru', 'Hyderabad',      'Pune',     'Delhi', 'Bangalore',  'Hyderbad',
   'Kolkata',    'Mumbai']
Length: 8, dtype: str

In [57]:
df.groupby('region')['profit'].sum().sort_values(ascending=False).head()

region
Kolkata      456963.06
Mumbai       436952.68
Delhi        414517.66
Pune         404040.56
Hyderabad    249907.41
Name: profit, dtype: float64

In [58]:
df['region'].value_counts()

region
Delhi        322
Mumbai       322
Kolkata      317
Pune         290
Hyderabad    201
Bangalore    166
Bengaluru    158
Hyderbad     108
Name: count, dtype: int64

In [59]:
df['day'] = df['order_date'].dt.day_name()

In [60]:
df['month'] = df['order_date'].dt.month_name()

In [61]:
df['month_num'] = df['order_date'].dt.month

In [62]:
df.head()

,order_id,gender_category,product_line,product_name,size,units_sold,mrp,discount_applied,revenue,order_date,sales_channel,region,profit,transaction_type,revenue_clean,day,month,month_num
0,2000,Kids,Training,SuperRep Go,M,NaN,NaN,0.47,0.0,2024-03-09,Online,Bengaluru,-770.45,Unknown,NaN,Saturday,March,3
1,2001,Women,Soccer,Tiempo Legend,M,3.0,4957.93,0.00,0.0,2024-07-09,Retail,Hyderabad,-112.53,Sale,14873.79,Tuesday,July,7
3,2003,Kids,Lifestyle,Blazer Mid,L,NaN,9673.57,0.00,0.0,2024-04-10,Online,Pune,3376.85,Unknown,NaN,Wednesday,April,4
4,2004,Kids,Running,React Infinity,XL,NaN,NaN,0.00,0.0,2024-09-12,Retail,Delhi,187.89,Unknown,NaN,Thursday,September,9
6,2006,Men,Training,SuperRep Go,M,NaN,6819.78,0.00,0.0,2025-04-06,Online,Bangalore,1802.09,Unknown,NaN,Sunday,April,4

In [63]:
df.head()

,order_id,gender_category,product_line,product_name,size,units_sold,mrp,discount_applied,revenue,order_date,sales_channel,region,profit,transaction_type,revenue_clean,day,month,month_num
0,2000,Kids,Training,SuperRep Go,M,NaN,NaN,0.47,0.0,2024-03-09,Online,Bengaluru,-770.45,Unknown,NaN,Saturday,March,3
1,2001,Women,Soccer,Tiempo Legend,M,3.0,4957.93,0.00,0.0,2024-07-09,Retail,Hyderabad,-112.53,Sale,14873.79,Tuesday,July,7
3,2003,Kids,Lifestyle,Blazer Mid,L,NaN,9673.57,0.00,0.0,2024-04-10,Online,Pune,3376.85,Unknown,NaN,Wednesday,April,4
4,2004,Kids,Running,React Infinity,XL,NaN,NaN,0.00,0.0,2024-09-12,Retail,Delhi,187.89,Unknown,NaN,Thursday,September,9
6,2006,Men,Training,SuperRep Go,M,NaN,6819.78,0.00,0.0,2025-04-06,Online,Bangalore,1802.09,Unknown,NaN,Sunday,April,4

In [64]:
day_order = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']

In [65]:
df['day'] = pd.Categorical(df['day'], categories=day_order, ordered=True)

In [66]:
df.groupby('day')['profit'].sum()

day
Monday       330622.59
Tuesday      389681.36
Wednesday    361344.19
Thursday     363155.50
Friday       326236.67
Saturday     367642.69
Sunday       424856.17
Name: profit, dtype: float64

In [67]:
df['day'].value_counts()

day
Saturday     294
Sunday       287
Tuesday      272
Thursday     271
Monday       266
Wednesday    260
Friday       234
Name: count, dtype: int64

In [68]:
month_order = ['January', 'February', 'March', 'April', 'May', 'June',
'July', 'August', 'September', 'October', 'November', 'December']

df['month'] = pd.Categorical(df['month'], categories=month_order, ordered=True)

In [69]:
df.groupby('month')['profit'].sum()

month
January      209831.64
February     190598.98
March        231291.72
April        217550.96
May          209037.16
June         193558.79
July         186267.96
August       234261.40
September    229737.06
October      190940.28
November     255135.28
December     215327.94
Name: profit, dtype: float64

In [70]:
df['month'].value_counts()

month
January      175
November     171
May          170
October      168
August       166
March        163
April        162
December     154
September    144
February     141
July         138
June         132
Name: count, dtype: int64

In [71]:
df

,order_id,gender_category,product_line,product_name,size,units_sold,mrp,discount_applied,revenue,order_date,sales_channel,region,profit,transaction_type,revenue_clean,day,month,month_num
0,2000,Kids,Training,SuperRep Go,M,NaN,NaN,0.47,0.0,2024-03-09,Online,Bengaluru,-770.45,Unknown,NaN,Saturday,March,3
1,2001,Women,Soccer,Tiempo Legend,M,3.0,4957.93,0.00,0.0,2024-07-09,Retail,Hyderabad,-112.53,Sale,14873.79,Tuesday,July,7
3,2003,Kids,Lifestyle,Blazer Mid,L,NaN,9673.57,0.00,0.0,2024-04-10,Online,Pune,3376.85,Unknown,NaN,Wednesday,April,4
4,2004,Kids,Running,React Infinity,XL,NaN,NaN,0.00,0.0,2024-09-12,Retail,Delhi,187.89,Unknown,NaN,Thursday,September,9
6,2006,Men,Training,SuperRep Go,M,NaN,6819.78,0.00,0.0,2025-04-06,Online,Bangalore,1802.09,Unknown,NaN,Sunday,April,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2494,4494,Women,Training,ZoomX Invincible,L,NaN,NaN,0.00,0.0,2025-12-02,Online,Kolkata,1357.29,Unknown,NaN,Tuesday,December,12
2495,4495,Kids,Basketball,Kyrie Flytrap,XL,3.0,NaN,0.00,0.0,2025-05-14,Online,Pune,2.97,Sale,NaN,Wednesday,May,5
2497,4497,Men,Soccer,Tiempo Legend,7,NaN,6647.60,0.52,0.0,2025-02-07,Retail,Bangalore,-918.14,Unknown,NaN,Friday,February,2
2498,4498,Women,Training,ZoomX Invincible,unknown,4.0,5358.70,0.00,0.0,2024-11-12,Online,Mumbai,3352.29,Sale,21434.80,Tuesday,November,11
2499,4499,Women,Running,Air Zoom,M,NaN,5550.99,0.00,0.0,2024-11-23,Retail,Mumbai,2453.57,Unknown,NaN,Saturday,November,11